trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
  - script: java -version
    displayName: 'Check Java Version'

  - task: Maven@4
    displayName: 'Build and Run Playwright Java Tests'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      options: '-Dmaven.test.failure.ignore=false'
      javaHomeOption: 'Path'
      jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'  # For Ubuntu agents (or leave blank for default)
      mavenVersionOption: 'Default'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishTestResults@2
    displayName: 'Publish JUnit Test Results'
    inputs:
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      testRunTitle: 'Playwright Java Test Results'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish HTML Test Report'
    inputs:
      PathtoPublish: 'target/cucumber-html-reports'
      ArtifactName: 'TestReport'
