# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev
    displayName: 'Dev Stage'
    jobs:
      - job: DevJob
        steps:
          - script: echo "deploy to SIT"
            displayName: 'Dev - Deploy to SIT'

  - stage: SIT
    displayName: 'SIT Stage'
    jobs:
      - job: SITJob
        steps:
          - script: echo "deploy to UAT"
            displayName: 'SIT - Deploy to UAT'

  - stage: UAT
    displayName: 'UAT Stage'
    jobs:
      - job: UATJob
        continueOnError: true  # Equivalent to Jenkins catchError
        steps:
          - task: GitClone@1
            inputs:
              repository: 'https://github.com/balasivarathri/playwrightwithjava.git'
              cleanOptions: 'true'

          - script: |
              mvn clean install
            displayName: 'Build with Maven'

  - stage: PublishReport
    displayName: 'Publish HTML Report'
    jobs:
      - job: ReportJob
        steps:
          - task: PublishBuildArtifacts@1
            displayName: 'Publish HTML Report'
            inputs:
              PathtoPublish: 'target/cucumber-html-reports'
              ArtifactName: 'BALA_HTML_Report'
              publishLocation: 'Container'

