trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Dev
    displayName: 'Dev Environment'
    jobs:
      - job: DevJob
        steps:
          - script: echo "Deploy to SIT"
            displayName: 'Dev - Deploy to SIT'

  - stage: SIT
    displayName: 'SIT Environment'
    jobs:
      - job: SITJob
        steps:
          - script: echo "Deploy to UAT"
            displayName: 'SIT - Deploy to UAT'

  - stage: UAT
    displayName: 'UAT Environment'
    jobs:
      - job: UATJob
        steps:
          - script: java -version
            displayName: 'Check Java Version'

          # Install Node.js (for Swagger API server)
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          # ✅ Print public IP of the agent
          - script: powershell -Command "Invoke-RestMethod -Uri 'https://api.ipify.org'"
            displayName: 'Print Agent Public IP'

          # List root directory to verify structure
          - script: dir
            displayName: 'List Root Directory'

          # Install Swagger API server dependencies
          - script: |
              cd swagger-api-server
              npm install
            displayName: 'Install Swagger API Server Dependencies'

          # Start Swagger API Server in background using PowerShell
          - powershell: |
              cd swagger-api-server
              Start-Process "node" -ArgumentList "server.js" -NoNewWindow
              Start-Sleep -Seconds 10
            displayName: 'Start Swagger API Server in Background'

          # Run Playwright Java Tests
          - task: Maven@4
            displayName: 'Build and Run Playwright Java Tests'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean test'
              options: '-Dmaven.test.failure.ignore=false'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              mavenVersionOption: 'Default'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'

          # Publish JUnit Test Results
          - task: PublishTestResults@2
            displayName: 'Publish JUnit Test Results'
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'Playwright Java Test Results'
              failTaskOnFailedTests: true

          # Publish HTML Test Report Artifact
          - task: PublishBuildArtifacts@1
            displayName: 'Publish HTML Test Report'
            inputs:
              PathtoPublish: 'target/cucumber-html-reports'
              ArtifactName: 'Bala HTML Test Report'

          # Publish HTML Test Report Viewer (optional UI viewer task)
          - task: PublishHtmlReport@1
            inputs:
              reportDir: 'target/cucumber