trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  javaVersion: '17'
  mavenVersion: '4'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'                 # Java version
    jdkArchitectureOption: 'x64'     # Architecture
    jdkSourceOption: 'Microsoft'     # ✅ Required: Use Microsoft-built JDK
  displayName: 'Install Java 17'

  - task: Maven@4
    displayName: 'Build and Run Playwright Java Tests'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      options: '-Dmaven.test.failure.ignore=false'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      mavenVersionOption: 'Default'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishTestResults@2
    displayName: 'Publish JUnit Test Results'
    inputs:
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      testRunTitle: 'Playwright Java Test Results'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish HTML Test Report'
    inputs:
      PathtoPublish: 'target/cucumber-html-reports'
      ArtifactName: 'TestReport'
