trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

stages: 
  - stage: Dev
    displayName: 'Dev Environment'
    jobs:
      - job: DevJob
        steps:
          - script: echo "Deploy to SIT"
            displayName: 'Dev - Deploy to SIT'

  - stage: SIT
    displayName: 'SIT Environment'
    jobs:
      - job: SITJob
        steps:
          - script: echo "Deploy to UAT"
            displayName: 'SIT - Deploy to UAT'

  - stage: UAT
    displayName: 'UAT Environment'
    jobs:
      - job: UATJob
        steps:
          - script: java -version
            displayName: 'Check Java Version'

          - task: Maven@4
            displayName: 'Build and Run Playwright Java Tests'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean test'
              options: '-Dmaven.test.failure.ignore=false'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              mavenVersionOption: 'Default'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'

          - task: PublishTestResults@2
            displayName: 'Publish JUnit Test Results'
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'Playwright Java Test Results'
              failTaskOnFailedTests: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish HTML Test Report'
            inputs:
              PathtoPublish: 'target/cucumber-html-reports'
              ArtifactName: 'Bala HTML Test Report'

          - task: PublishHtmlReport@1
            inputs:
              reportDir: 'target/cucumber-html-reports/overview-features.html'
              reportIndexFile: 'overview-features.html'
              useFilenameTabs: true
              reportName: 'UI Automation Report'